version: "3.9"

services:
  fabrizzio-service:
    build:
      context: ./fabrizzio-service
    ports:
      - "3001:3001"
    restart: always
    networks:
      - nodejs-network

  sumaran-service:
    build:
      context: ./sumaran-service
    ports:
      - "3000:3000"
    restart: always
    networks:
      - nodejs-network

networks:
  nodejs-network:
    driver: bridge
