name: Deploy NodeJS App Infrastructure and Code

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  LAMBDA_NAME: arn:aws:lambda:us-east-2:676206932076:function:BackendLambdaFunction
  BUCKET_NAME: arn:aws:s3:::hola-mundo-cloud-bucket

jobs:
  backend:
    name: Deploy Backend (Lambda Function)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Zip Backend Code
        run: |
          cd backend
          zip -r ../lambda_function.zip .

      - name: Update Lambda Code
        run: |
          aws lambda update-function-code --function-name ${{ env.LAMBDA_NAME }} \
            --zip-file fileb://lambda_function.zip

  frontend:
    name: Deploy Frontend (S3 Static Website)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync Frontend to S3
        run: |
          aws s3 sync frontend/ s3://${{ env.BUCKET_NAME }} \
            --acl public-read
