name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  EC2_HOST: ec2-3-137-193-161.us-east-2.compute.amazonaws.com  # Define EC2_HOST globally

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          echo "Running as user $(whoami)"
          echo "INSTALLING NPM ......"
          npm install

  deploy:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - name: Set up SSH key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
          chmod 600 ec2_key.pem

      - name: Delete previous distribution on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@"$EC2_HOST" << 'EOF'
            #!/bin/bash

            # Stop all running Docker containers
            echo "Stopping all Docker containers..."
            sudo docker stop $(sudo docker ps -q) || echo "No running containers to stop."

            # Remove all Docker containers
            echo "Removing all Docker containers..."
            sudo docker rm $(sudo docker ps -aq) || echo "No containers to remove."

            # Remove all Docker images
            echo "Removing all Docker images..."
            sudo docker rmi $(sudo docker images -q) || echo "No Docker images to remove."

            # Clean up old application directory
            echo "Removing the old application directory..."
            sudo rm -rf /home/ec2-user/nodeapp

            # List contents of the application directory for verification
            echo "Listing /home/ec2-user/:"
            ls /home/ec2-user/
          EOF

      - name: Build and Run Docker Container on EC2
        run: |
          ssh -i ec2_key.pem -o StrictHostKeyChecking=no ec2-user@"$EC2_HOST" << 'EOF'
            #!/bin/bash

            # Clone your Node.js app from the Git repository (replace with your repo)
            cd /home/ec2-user
            git clone https://github.com/Fabrizzio-Esquivel-UNAS/HolaMundoCloud_APIGatewayEdition.git nodeapp
            cd nodeapp

            # Run the services with Docker Compose
            sudo docker-compose up --build -d
          EOF

      - name: Clean up SSH key
        run: rm ec2_key.pem